server:
  port: ${appserver.port:8080}
spring:
  application:
    name: "r2dbc-postgres-100-memleak"
  r2dbc:
    username: ${POSTGRES_USERNAME:local}
    password: ${POSTGRES_PASSWORD:local}
    url: r2dbc:postgresql://${POSTGRES_URL:localhost:5432/flyway-test-db}
  flyway:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/flyway-test-db}
    locations: classpath:db/migration
    password: ${POSTGRES_PASSWORD:local}
    user: ${POSTGRES_USERNAME:local}
